# Generated by Django 5.1.2 on 2024-11-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthobbies',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
