# Generated by Django 5.1.2 on 2024-11-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0003_alter_studenthobbies_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthobbies',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
